### ISSUE TITLE
Material UI v1.0.0 porting

### ISSUE THREAD

**Issue by salamaashoush** [Sharlaan/material-ui-superselectfield#81] opened 2017-10-24 20:02 UTC
`/node_modules/material-ui-selectfield/es/SelectField.js
Module not found: Can't resolve 'material-ui/svg-icons/navigation/check' in 'node_modules/material-ui-selectfield/es'`

**Comment by Sharlaan** [comment] 2017-10-24 21:51
duplicate of #71

**Closed as completed by Sharlaan** 2017-10-24 21:51 UTC
